# Generated by Django 4.2 on 2023-05-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('generate_pdf', 'Can generate PDF document based on Post')]},
        ),
    ]
