# Generated by Django 4.2 on 2023-05-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_be_shared', 'Post can be shared by clicking Share button')]},
        ),
    ]
